version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pce_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pce_db
      MYSQL_USER: pce_web
      MYSQL_PASSWORD: pce_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
